import Head from 'next/head';
import Header from '../Components/Header';
import Navbar from '../Components/Navbar';
import Results from '../Components/Results';
import Requist from '../utils/Requist';

export default function Home({ results }) {
	return (
		<div>
			<Head>
				<title>HULU-App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Navbar />
			<Results Results={results} />
		</div>
	);
}

export async function getServerSideProps(context) {
	const genre = context.query.genre;

	const request = await fetch(`https://api.themoviedb.org/3${Requist[genre]?.url || Requist.fetchTrending.url}`).then((res) => res.json())
	return {
		props: {
			results: request.results
		}
	}
}
